<a href="https://colab.research.google.com/github/RajeeveTD007/2026-FDP-DSU/blob/main/DAy2-NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Load in NumPy (remember to pip install numpy first)

In [ ]:
import numpy as np

In [ ]:
help(np.array)

In [ ]:
### The Basics

In [ ]:
a = np.array([1,2,3], dtype='int64')
print(a)
print(a.dtype)
a.ndim
a.shape
a.size

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.ndim
b.shape
b.size

In [ ]:
# Get Dimension
b.ndim

In [ ]:
# Get Shape
a.shape

In [ ]:
# Get Type
b.dtype

In [ ]:
# Get Size
a.itemsize


In [ ]:
# Get total size
a.nbytes


In [ ]:
# Get number of elements
b.size

In [ ]:
### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

In [ ]:
a.ndim

In [ ]:
# Get a specific element [r, c]
a[0,0]

In [ ]:
# Get a specific row
a[0, :]

In [ ]:
# Get a specific column
a[:, 2]

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, -1:-6:-2]

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

In [ ]:
# Get specific element (work outside in)
b[1,1,1]

In [ ]:
# replace
b[:,0,:] = [[9,9],[8,8]]

In [ ]:
b

In [ ]:
### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

In [ ]:
# All 1s matrix
c=np.ones((4,2,2,2), dtype='int32')
c.ndim

In [ ]:
# Any other number
np.full((2,3), 999)

In [ ]:
# Any other number (full_like)
np.full_like(b, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(0,6, size=(4,3))

In [ ]:
# The identity matrix
np.identity(3)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [18]:
output = np.ones((5,5))
#print(output)
z = np.zeros((3,3))
z[1,1] = 9
#print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
##### Be careful when copying arrays!!!

In [25]:
a = np.array([1,2,3])
b = a.copy()
b = a
b[0] = 100
print(a)

[100   2   3]


In [ ]:
### Mathematics

In [26]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a + 2

array([3, 4, 5, 6])

In [28]:
a - 2

array([-1,  0,  1,  2])

In [29]:
a * 2

array([2, 4, 6, 8])

In [30]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [31]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [32]:
a ** 2

array([ 1,  4,  9, 16])

In [33]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [ ]:
##### Linear Algebra

In [37]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [ ]:
##### Statistics

In [38]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(stats)

np.int64(1)

In [42]:
np.max(stats, axis=1)

array([3, 6])

In [44]:
np.sum(stats, axis=1)

array([ 6, 15])

In [ ]:
### Reorganizing Arrays

In [46]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
import numpy as np

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

# Reshape into (2, 3)
after = before.reshape((2, 2, 2))  # Corrected to match the total number of elements
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])
#np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
### Miscellaneous
##### Load Data from File

In [56]:
filedata = np.genfromtxt('data.txt', delimiter=' ')
filedata = filedata.astype('int32')
print(filedata)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
##### Boolean Masking and Advanced Indexing

In [57]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [58]:
#Scientific Computing
import numpy as np

arr = np.array([1, 4, 9, 16])

print("Square Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Exponential:", np.exp([1,2]))
print("Log:", np.log([1,2]))

Square Root: [1. 2. 3. 4.]
Square: [  1  16  81 256]
Exponential: [2.71828183 7.3890561 ]
Log: [0.         0.69314718]


In [59]:
#Array Iteration

arr = np.array([[1,2],[3,4]])

for x in np.nditer(arr):
    print(x)

1
2
3
4


In [60]:
#Joining Arrays
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [68]:
#Splitting Arrays
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(np.array_split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [71]:
#Searching Arrays
import numpy as np

arr = np.array([10,20,30,20,50])

print(np.where(arr==20))

(array([1, 3]),)


In [72]:
#sorting
import numpy as np

arr = np.array([40,10,50,20])

print(np.sort(arr))

[10 20 40 50]


In [73]:
#FIltering
import numpy as np

arr = np.array([10,15,20,25,30])

print(arr[arr>20])

[25 30]


Broadcasting performs operations between arrays of different shapes.

In [74]:
#Broadcasting
import numpy as np

arr = np.array([1,2,3])

print(arr + 10)

[11 12 13]


Vector Quantization


Convert continuous values into discrete groups.

In [75]:
import numpy as np

data = np.array([5,15,25,35,45])

bins = [10,20,30,40]

print(np.digitize(data,bins))

# https://chatgpt.com/s/t_6a439cd5c8888191807b8d50721ee208




[0 1 2 3 4]
